name: "publish"

on:
  push:
    tags:
      - "*"
permissions:
  contents: write
  id-token: write

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - name: Update package.json version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          jq --arg version "$TAG" '.version = $version' package.json > tmp.$$.json && mv tmp.$$.json package.json
      - name: Compile typescript
        run: bun run build

      - name: Publish to npm
        run: npm publish --provenance --access public

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
